# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_info',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_code', models.IntegerField(max_length=10)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='customer_info',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='extra_info',
            fields=[
                ('ex_id', models.AutoField(primary_key=True, serialize=False)),
                ('add_type', models.CharField(max_length=10)),
                ('value', models.CharField(max_length=30)),
                ('cust_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer_info')),
            ],
        ),
        migrations.AddField(
            model_name='address_info',
            name='cust_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.customer_info'),
        ),
    ]
