# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20181115_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='customer_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
