# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_auto_20181115_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_info',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
